version: "3.0"

services:
  api:
    container_name: coffee_delivery_remix_api
    image: coffee_delivery_remix/api
    restart: always
    build: ../api
    volumes:
      - coffee_delivery_remix:/var/lib/api
      - ../api:/api
    ports:
      - "9000:9000"
    env_file:
      - ../api/.env
    depends_on:
      - db

  db: 
    container_name: coffee_delivery_remix_db
    image: coffee_delivery_remix/db
    restart: always
    build: ../db
    environment:
      POSTGRES_PASSWORD: "1459"
      POSTGRES_USER: "user_coffee"
    volumes:
      - coffee_delivery_remix:/var/lib/postgresql/data
    ports:
      - "6000:6000"
    command: -p 6000
    
networks:
  default:
    name: coffee_delivery_remix
    external: true

volumes:
  coffee_delivery_remix:
    external: true