version: "1.0"

services:
  front: 
    container_name: coffee_delivery_remix_front
    image: coffee_delivery_remix/front
    restart: always
    network_mode: "host"
    build: .
    volumes:
      - .:/front/
  