version: "2.2"

services:
  db: 
    container_name: coffe_delivery_remix_db
    image: coffe_delivery_remix/database
    restart: always
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_PASSWORD: "1459"
      POSTGRES_USER: "user_coffe"
    volumes:
      - coffe_delivery_remix:/var/lib/postgresql/data
    ports:
      - "6000:6000"
    command: -p 6000
volumes:
  coffe_delivery_remix:
    external: true