version: "1.1"

services:
  db: 
    container_name: coffe_delivery_remix_db
    image: coffe_delivery_remix/database
    restart: always
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_PASSWORD: "1459"
      POSTGRES_USER: "user_coffe"
    volumes:
      - coffe_delivery_remix_db:/var/lib/postgresql/coffe-delivery-remix/data
    ports:
      - "5432:5432"
volumes:
  coffe_delivery_remix_db:
    external: true